version: "3.9"
services:
  nextjs:
    image: hub.tnxs.net/work/web/web_prod
    container_name: nextjs
    ports:
      - "3000:3000"
    restart: always
  nginx:
    image: hub.tnxs.net/work/web/nginx_prod:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/ssl:/etc/nginx/ssl:ro
    restart: always
